# Make sure the port matches your MySQL installation (usually 3306)
spring.datasource.url=jdbc:mysql://localhost:3305/edutrack_db?useSSL=false
spring.datasource.username=root
spring.datasource.password=@swaroop2004

# This helps Hibernate match your manual SQL changes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true