spring.application.name=edutrack-app

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3305/edutrack_db
spring.datasource.username=root
spring.datasource.password=@swaroop2004

# Show SQL in Console (Helpful for debugging)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update